version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: php74-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  php:
    build: ./php
    container_name: php74-php
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
