version: '3.8'
services:
  php:
    build: ./php
    container_name: php74-php
    ports:
      - "8074:80"
    volumes:
      - ./www:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini